//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "fruit")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub name: String,
  pub cake_id: Uuid,
  pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::cake::Entity",
    from = "Column::CakeId",
    to = "super::cake::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Cake,
}

impl Related<super::cake::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Cake.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
