//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::cake::Entity as Cake;
pub use super::cake_filling::Entity as CakeFilling;
pub use super::cooker::Entity as Cooker;
pub use super::filling::Entity as Filling;
pub use super::fruit::Entity as Fruit;
